// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVBkGdGXt3ucizJg8TB4hsUaWVMefjxr8',
    appId: '1:384168238964:web:5afae80fb8c41e8b8d5621',
    messagingSenderId: '384168238964',
    projectId: 'parkingcardb-2d8b0',
    authDomain: 'parkingcardb-2d8b0.firebaseapp.com',
    storageBucket: 'parkingcardb-2d8b0.firebasestorage.app',
    measurementId: 'G-06X2CDELDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj4TNzYIPMb8omYRuGeqIjWkxb5DdR-c4',
    appId: '1:384168238964:android:efb88ac7642454c98d5621',
    messagingSenderId: '384168238964',
    projectId: 'parkingcardb-2d8b0',
    storageBucket: 'parkingcardb-2d8b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAp-qGJ8oFLSvrfMeHmNTYjbJtGbdfrbg',
    appId: '1:384168238964:ios:3aea8248ce6721f68d5621',
    messagingSenderId: '384168238964',
    projectId: 'parkingcardb-2d8b0',
    storageBucket: 'parkingcardb-2d8b0.firebasestorage.app',
    iosBundleId: 'com.example.parkingcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAp-qGJ8oFLSvrfMeHmNTYjbJtGbdfrbg',
    appId: '1:384168238964:ios:3aea8248ce6721f68d5621',
    messagingSenderId: '384168238964',
    projectId: 'parkingcardb-2d8b0',
    storageBucket: 'parkingcardb-2d8b0.firebasestorage.app',
    iosBundleId: 'com.example.parkingcar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVBkGdGXt3ucizJg8TB4hsUaWVMefjxr8',
    appId: '1:384168238964:web:f89d97cbc312cc1c8d5621',
    messagingSenderId: '384168238964',
    projectId: 'parkingcardb-2d8b0',
    authDomain: 'parkingcardb-2d8b0.firebaseapp.com',
    storageBucket: 'parkingcardb-2d8b0.firebasestorage.app',
    measurementId: 'G-NK6N0N6285',
  );
}
